// Repo-owned. importOrder is generated from modules/fsd/layers.json — do not
// hand-edit that block. Regenerate with /thinkit:harness-bootstrap next.
export default {
  semi: true,
  tabWidth: 2,
  printWidth: 100,
  singleQuote: true,
  jsxSingleQuote: true,
  bracketSpacing: true,
  arrowParens: 'avoid',
  trailingComma: 'all',
  quoteProps: 'consistent',
  plugins: ['@ianvs/prettier-plugin-sort-imports', 'prettier-plugin-tailwindcss'],
  importOrder: [
    '^server-only$',
    '<BUILTIN_MODULES>',
    '',
    '<THIRD_PARTY_MODULES>',
    '',
    '^app/(.*)$',
    '',
    '^@app/(.*)$',
    '',
    '^src/screens/(.*)$',
    '',
    '^@widgets/(.*)$',
    '',
    '^@features/(.*)$',
    '',
    '^src/entities/(.*)$',
    '',
    '^@shared/(.*)$',
    '',
    '^@db/(.*)$',
    '',
    '^src/(.*)$',
    '',
    '^[.]',
  ],
};
